// Triangular, pentagonal, and hexagonal
// Problem 45
//
// Triangle, pentagonal, and hexagonal numbers are generated by the following
// formulae:
//
// Triangle		Tn=n(n+1)/2		1, 3, 6, 10, 15, ...
// Pentagonal		Pn=n(3n−1)/2		1, 5, 12, 22, 35, ...
// Hexagonal		Hn=n(2n−1)		1, 6, 15, 28, 45, ...
//
// It can be verified that T285 = P165 = H143 = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.
package main

import "fmt"

func main() {
	isP := make(map[int]bool)
	isH := make(map[int]bool)

	for n := 1; ; n++ {
		isP[n*(3*n-1)/2] = true
		isH[n*(2*n-1)] = true

		t := n * (n + 1) / 2
		if t > 40755 && isP[t] && isH[t] {
			fmt.Println(t)
			return
		}
	}
}
